baseurl = "https://ridiculous.software"
languageCode = "en-us"
theme = "hello-friend-ng"
relativeURLs = false
canonifyurls = true

[params]
# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = ""

# "light" or "dark"
defaultTheme = "dark"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 3

# Show reading time in minutes for posts
showReadingTime = false

# Show table of contents at the top of your posts (defaults to false)
# Alternatively, add this param to post front matter for specific posts
# toc = true

# Show full page content in RSS feed items
#(default is Description or Summary metadata in the front matter)
# rssFullText = true

[languages]
[languages.en]
title = "Stupid Technology"
subtitle = "A Ridiculous Software Project"
keywords = "technology!"
copyright = "A Ridiculous Software Project"
menuMore = "Show more"
writtenBy = "Written by"
readMore = ""
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
# leave empty to disable, enter display text to enable
# lastModDisplay = ""

[languages.en.params.logo]
logoText = "Stupid Technology"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "experiments"
name = "Experiments"
url = "/experiments"
[[languages.en.menu.main]]
identifier = "research"
name = "Research"
url = "/research"
# [[languages.en.menu.main]]
#   identifier = "education"
#   name = "Education"
#   url = "/CP/introduction"
